name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le repo
      uses: actions/checkout@v3

    - name: Déployer avec rsync via SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        rsync -avz --exclude='.env' -e "ssh -o StrictHostKeyChecking=no -i private_key" . ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/tanguy/apps/portfolio
        rm -f private_key

    - name: Lancer le conteneur Docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/tanguy/apps/portfolio
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
